### ISSUE TITLE
Server (Cauldron 1448) wont start with Zap Apples Mod

### ISSUE THREAD

**Issue by ZPinka** [ChioriGreene/ZapAppleMod#2]
It seems that the ZapApples mod is crashing my server. We use Cauldron 1448. After i removed the mod from my server everything went fine.

**Comment by BarelyAPrincess** [comment]
Can you please upload a crash report? I can't find causes without at least a stack trace.

**Comment by ZPinka** [comment]
http://pastebin.com/NUfaL0qC

**Comment by BarelyAPrincess** [comment]
The issue has been resolved. Offical build can be downloaded here: http://minecraft.curseforge.com/mc-mods/59733-zap-apple-mod/files/2243104
