### ISSUE TITLE
Latest Zap Apples crashes client

### ISSUE THREAD

**Issue by ZPinka** [ChioriGreene/ZapAppleMod#3]
Apparently is now the problem on the client. After several crashes I just used Zap Apples and removed all other mods and it still crashes. Here is a pastebin: http://pastebin.com/aeKR9k06

I use Forge 1448.

**Comment by BarelyAPrincess** [comment]
Here: http://minecraft.curseforge.com/mc-mods/59733-zap-apple-mod/files/2243462
